all:	libcirco.a
ROOT=../..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I. -I$(ROOT) \
	-I../common \
	-I../neatogen \
	-I../dotgen \
	-I../pack \
	-I../gvc \
	-I../pathplan \
	-I../graph \
	-I../cdt \
	-I../gd

DEFINES = -DHAVE_CONFIG_H

OBJS = circularinit.o nodelist.o block.o edgelist.o stack.o circular.o \
       deglist.o blocktree.o blockpath.o circpos.o nodeset.o

HFILES = circular.h nodelist.h edgelist.h deglist.h stack.h \
         block.h

libcirco.a : $(OBJS)
	$(RM) libcirco.a
	$(AR) cr libcirco.a $(OBJS)
	$(RANLIB) libcirco.a

BASEH = circular.h nodelist.h block.h stack.h

block.o : $(BASEH)
blockpath.o : $(BASEH) blockpath.h edgelist.h nodeset.h deglist.h
blocktree.o : blocktree.h $(BASEH)
circpos.o : blockpath.h $(BASEH)
circular.o : blocktree.h circpos.h $(BASEH)
circularinit.o : $(BASEH)
deglist.o : deglist.h blockpath.h $(BASEH)
edgelist.o : edgelist.h
nodelist.o : $(BASEH)
nodeset.o : nodeset.h
stack.o : $(BASEH)

install: libcirco.a
	$(MKPATH) $(INCDIR)
	$(INSTALL) circo.h $(INCDIR)
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libcirco.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
