all:	libgvrender.a

include ../../Config.mk
include ../../makearch/$(ARCH)

INCS =  -I. \
        -I../.. \
        -I../../cdt \
        -I../../pathplan \
	-I../../graph \
	-I../common \
	$(EXTLIB_INC)

DEFINES = -DHAVE_CONFIG_H

HDRS = gvrender.h gvrenderint.h

OBJS = gvrender.o gvcontext.o gvjobs.o gvlang.o gvconfig.o

libgvrender.a : $(OBJS)
	$(RM) libgvrender.a
	$(AR) cr libgvrender.a $(OBJS)
	$(RANLIB) libgvrender.a

install: libgvrender.a 
	$(MKPATH) $(INCDIR)
	$(INSTALL) gvrender.h gvrenderint.h $(INCDIR)
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libgvrender.a $(LIBDIR)

$(OBJS) : $(HDRS)

clean:
	$(RM) core *.o

distclean: clean
	$(RM) *.a
