all:	libgvc.a
ROOT=../..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =  -I. \
        -I$(ROOT) \
        -I../cdt \
        -I../pathplan \
	-I../graph \
	-I../common \
	$(EXTLIB_INC)

DEFINES = -DHAVE_CONFIG_H -DGVLIBDIR=\"$(LIBDIR)\"

INST_HDRS = gvc.h gvcint.h gvcjob.h gvcext.h gvplugin.h \
	gvplugin_render.h gvplugin_device.h \
	gvplugin_layout.h gvplugin_textlayout.h \
	gvplugin_usershape.h

NOINST_HDRS = gvcproc.h

OBJS = gvrender.o gvlayout.o gvdevice.o gvcontext.o gvjobs.o \
	gvplugin.o gvconfig.o gvevent.o gvtextlayout.o gvusershape.o gvc.o

libgvc.a : $(OBJS)
	$(RM) libgvc.a
	$(AR) cr libgvc.a $(OBJS)
	$(RANLIB) libgvc.a

install: libgvc.a 
	$(MKPATH) $(INCDIR)
	$(INSTALL) $(HDRS) $(INCDIR)
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libgvc.a $(LIBDIR)

$(OBJS) : $(HDRS)

clean:
	$(RM) core *.o

distclean: clean
	$(RM) *.a
