all:	libgvc.a
ROOT=../..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =  -I. \
        -I$(ROOT) \
        -I../cdt \
        -I../pathplan \
	-I../graph \
	-I../common \
	$(EXTLIB_INC)

DEFINES = -DHAVE_CONFIG_H

HDRS = gvc.h gvcint.h gvplugin_render.h \
	gvplugin_layout.h gvplugin.h

OBJS = gvrender.o gvlayout.o gvcontext.o gvjobs.o \
	gvemit.o gvplugin.o gvconfig.o

libgvc.a : $(OBJS)
	$(RM) libgvc.a
	$(AR) cr libgvc.a $(OBJS)
	$(RANLIB) libgvc.a

install: libgvc.a 
	$(MKPATH) $(INCDIR)
	$(INSTALL) gvc.h gvc.h $(INCDIR)
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libgvc.a $(LIBDIR)

$(OBJS) : $(HDRS)

clean:
	$(RM) core *.o

distclean: clean
	$(RM) *.a
