#define GVPLUGIN_CONFIG_FILE "config@GRAPHVIZ_PLUGIN_VERSION@"
#define GVPLUGIN_VERSION @GRAPHVIZ_PLUGIN_VERSION@
#define PACKAGE_BUGREPORT "http://www.graphviz.org/"
#define PACKAGE_NAME "graphviz"
#define PACKAGE_STRING "graphviz @GRAPHVIZ_VERSION_STRING@"
#define PACKAGE_TARNAME "graphviz"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "@GRAPHVIZ_VERSION_STRING@"
