#!/bin/sh

PACKAGEMAKER="/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker"

# configure for Universal Binaries
./configure --disable-dependency-tracking CFLAGS="-arch i386 -arch ppc" LDFLAGS="-arch i386 -arch ppc"
make

# make into the macosx build directory
rm -rf macosx/build/usr/local/*
make DESTDIR=$PWD/macosx/build install

# convert the build directory into a package
$PACKAGEMAKER --doc macosx/graphviz.pmdoc --out $1
