all:	libgvplugin_gd.a
ROOT=../..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =  -I. \
	-I$(ROOT) \
        -I../common \
        -I../gvc \
        -I../pathplan \
        -I../graph \
        -I../cdt \
        -I../gd \
        $(EXTLIB_INC)

DEFINES = -DHAVE_CONFIG_H

OBJS = gvplugin_gd.o gvrender_gd.o gvtextlayout_gd.o gvloadimage_gd.o

libgvplugin_gd.a : $(OBJS)
	$(RM) libgvplugin_gd.a
	$(AR) cr libgvplugin_gd.a $(OBJS)
	$(RANLIB) libgvplugin_gd.a

install: libgvplugin_gd.a
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libgvplugin_gd.a $(LIBDIR)

clean:
	$(RM) core *.o

distclean: clean
	$(RM) *.a ptest
