.de TQ
.  br
.  ns
.  TP \\$1
..
.TH GVMAP 1 "3 March 2011"
.SH NAME
gvmap \- find clusters and create a geographical map highlighting clusters.
.SH SYNOPSIS
.B gvmap
[\fB\-ekv?\fP]
[
.I options
]
[
.BI \-o
.I outfile
]
[ 
.I files
]
.SH DESCRIPTION
.B gvmap
takes as input a graph in DOT format, finds node clusters and produces a rendering of the graph as a geographic-style map, with clusters highlighted, in xdot format.
.P
The input graph must have node positions and width/height information defined, 
and nodes must not overlap.
.SH OPTIONS
The following options are supported:
.TP
.BI \-a " k"
The integer k specifies the average number of artificial points added along 
the bounding box of the labels. Such artificial points are added to avoid 
a country boundary cutting through the boundary box of the labels. Computing 
time is proportional to k; hence, for large graphs, a small value of k is 
suggested. If k = -1, a suitable value of k is automatically selected based on 
the graph size. By default k = -1.
.TP
.BI \-e
If specified, edges will be included in the final output.
.TP
.BI \-k
Increases randonesss of boundary
.TP
.BI \-s " d" 
The real number d specifies the depth of the shore in points. If 0, the depth is selected automatically. By default d = 0.
.TP
.BI \-v
Set verbose mode.

.SH EXAMPLES
.PP
Given a graph foo.gv, one way to generate a layout and highlight the clusters 
is to first select a layout engine with a suitable overlap removal method, then 
feed the output to gvmap, and finally render the map using specific graphics 
format. For example, the following pipeline
creates a map with edges in semi-transparent light gray and nodes laid 
out using sfdp:
.PP
sfdp -Goverlap=prism foo.gv | gvmap -e | neato -n2 -Ecolor=#55555522 -Tpng > foo.png
.PP
The shell script gvmap.sh provides a shorthand for such pipelines. For example, the
above pipeline can be achieved using
.PP
gvmap.sh -Ae -Ecolor=#55555522 -Tpng foo.gv > foo.png

.SH AUTHOR
Yifan Hu <yifanhu@research.att.com>
.SH "SEE ALSO"
.PP
gvmap.sh(1), sfdp(1), neato(1), gvpr(1)
.PP
E. R. Gansner, Y. Hu, S. G. Kobourov, "GMap: Visualizing graphs and clusters as maps," Proc. Pacific Vis. 2010, pp. 201\(hy208.
