ROOT=../..

include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

LOC_LIB = $(ROOT)/lib
LOC_PLUG=$(ROOT)/plugin

INCS =  -I$(LOC_LIB)/gvc -I$(LOC_LIB)/common -I$(ROOT) -I$(LOC_LIB)/cdt \
        -I$(LOC_LIB)/pathplan -I$(LOC_LIB)/gd -I$(LOC_LIB)/graph

ALLINCS = -I$(LOC_LIB)/dotgen -I$(LOC_LIB)/neatogen -I$(LOC_LIB)/twopigen \
          -I$(LOC_LIB)/circogen -I$(LOC_LIB)/fdpgen $(INCS)

DEFINES = -DHAVE_CONFIG_H

XLIBS = -L$(LOC_LIB)/pathplan -lpathplan \
        -L$(LOC_LIB)/graph -lgraph \
        -L$(LOC_LIB)/cdt -lcdt \
        -L$(LOC_LIB)/gd -lgd \
        $(EXTLIB_LIB) $(EXPAT_LIB) -lm

PLUGS = -L$(LOC_PLUG)/cairo -lgvplugin_cairo \
        -L$(LOC_PLUG)/layout -lgvplugin_layout \
        -L$(LOC_PLUG)/gd -lgvplugin_gd -L$(LOC_PLUG)/text -lgvplugin_text

LIBS = $(PLUGS) -L$(LOC_LIB)/neatogen -lneatogen \
       -L$(LOC_LIB)/dotgen -ldotgen \
       -L$(LOC_LIB)/circogen -lcircogen \
       -L$(LOC_LIB)/fdpgen -lfdpgen \
       -L$(LOC_LIB)/twopigen -ltwopigen \
       -L$(LOC_LIB)/pack -lpack \
       -L$(LOC_LIB)/common -lcommon \
       -L$(LOC_LIB)/gvc -lgvc \
       $(XLIBS)
DOTLIBS = ../../lib/common/libcommon.a ../../lib/dotgen/libdotgen.a \
          ../../lib/neatogen/libneatogen.a ../../lib/fdpgen/libfdpgen.a \
          ../../lib/twopigen/libtwopigen.a ../../lib/circogen/libcircogen.a


LIBDOTNEATO = libdotneato.a
OBJS = dot.o args.o plugins.o
SHLIBS = twopigen/libtwopi.a dotgen/libdot.a neatogen/libneato.a pack/libpack.a gvrender/libgvrender.a common/libcommon.a

all : dot $(LIBDOTNEATO)

dot : $(OBJS) $(DOTLIBS)
	$(CSLD) $(LDFLAGS) $(OBJS) $(LIBS) -o dot

dot.o : dot.c
	$(CC) -c $(CCFLAGS) $(DEFINES) $(INCS) dot.c

args.o : args.c
	$(CC) -c $(CCFLAGS) $(DEFINES) $(ALLINCS) args.c

plugins.o : plugins.c
	$(CC) -c $(CCFLAGS) $(DEFINES) $(ALLINCS) plugins.c

dotneato.o : dotneato.c
	$(CC) -I. -c $(CCFLAGS) $(DEFINES) $(ALLINCS) dotneato.c

$(LIBDOTNEATO) : dotneato.o
	$(AR) cr libdotneato.a dotneato.o
	$(RANLIB) libdotneato.a
	
install: all
	$(MKPATH) $(BINDIR)
	$(INSTALL) dot $(BINDIR)
	$(RM) $(BINDIR)/neato; $(LN) -s $(BINDIR)/dot $(BINDIR)/neato
	$(RM) $(BINDIR)/fdp; $(LN) -s $(BINDIR)/dot $(BINDIR)/fdp
	$(RM) $(BINDIR)/circo; $(LN) -s $(BINDIR)/dot $(BINDIR)/circo
	$(RM) $(BINDIR)/twopi; $(LN) -s $(BINDIR)/dot $(BINDIR)/twopi
	$(MKPATH) $(INCDIR)
	$(INSTALL) dotneato.h $(INCDIR)
	$(MKPATH) $(LIBDIR)
	$(INSTALL) $(LIBDOTNEATO) $(LIBDIR)/$(LIBDOTNEATO).$(VERSION)
	$(RM) -rf $(LIBDIR)/$(LIBDOTNEATO)
	$(LN) -s $(LIBDOTNEATO).$(VERSION) $(LIBDIR)/$(LIBDOTNEATO)
	$(MKPATH) $(MANDIR)
	$(INSTALL) dot.1 $(MANDIR)
	$(LN) -s $(MANDIR)/dot.1 $(MANDIR)/neato.1
	$(LN) -s $(MANDIR)/dot.1 $(MANDIR)/fdp.1
	$(LN) -s $(MANDIR)/dot.1 $(MANDIR)/circo.1
	$(LN) -s $(MANDIR)/dot.1 $(MANDIR)/twopi.1

distclean clean:
	$(RM) *.o core $(all)

