all:	libgvplugin_pango.a
ROOT=../..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =  -I. \
	-I$(ROOT) \
        -I../common \
        -I../gvc \
        -I../pathplan \
        -I../graph \
        -I../cdt \
        -I../gd \
        $(EXTLIB_INC)

DEFINES = -DHAVE_CONFIG_H

OBJS = gvloadimage_pango.o gvplugin_pango.o gvrender_pango.o gvtextlayout_pango.o

libgvplugin_pango.a : $(OBJS)
	$(RM) libgvplugin_pango.a
	$(AR) cr libgvplugin_pango.a $(OBJS)
	$(RANLIB) libgvplugin_pango.a

install: libgvplugin_pango.a
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libgvplugin_pango.a $(LIBDIR)

clean:
	$(RM) core *.o

distclean: clean
	$(RM) *.a ptest
