all : lneato

include ../Config.mk
include ../makearch/$(ARCH)

BIN_SCRIPTS = lneato

lneato: lneato.sh
	cp lneato.sh lneato
	chmod +x lneato

install:  $(BIN_SCRIPTS)
	$(MKPATH) $(BINDIR)
	$(INSTALL) $(BIN_SCRIPTS) $(BINDIR)

clean:
	true

distclean:
	true
