.TH INKPOT 1
.SH NAME
\fBinkpot\fR \- Color conversion tool
.SH SYNOPSIS
.ta .75i 1.5i 2.25i 3i 3.75i 4.5i 5.25i 6i
.PP
.nf
\f5
inkpot put_color put_schemes get_schemes

==> gotten_color

\fP
.fi
.SH DESCRIPTION
\fIinkpot\fP provides a facility for translating colors.

.SH AUTHOR
John Ellson (ellson@research.att.com), AT&T
