#! /bin/bash

dir="/home/dperry/graphviz2/doc/info"
cat ${dir}/command.html | sed -e /"DOCTYPE HTML"/,/"BODY BGCOLOR"/d -e /"Command-line Invocation"/d -e /"<\/BODY>"/d -e /"<\/HTML>"/d | \
sed -e s/"d:"/"d"/g -e s/'http:\/\/www.graphviz.org\/doc\/info\/output.html'/output-formats/g \
-e s/"output.html"/output-formats/g -e s/"attrs.html"/attrs/g \
> command_db

