#! /bin/bash

dir="/home/dperry/graphviz2/doc/info"
cat ${dir}/attrs.html | sed -e /"DOCTYPE HTML"/,/"BODY BGCOLOR"/d -e /"Node, Edge and Graph Attributes<\/H1>"/d \
-e /"<\/BODY>"/d -e /"<\/HTML>"/d | \
sed -e s/"d:"/"d"/g -e s/"k:"/"k"/g -e s/"a:"/"a"/g \
| sed -e s/'http:\/\/www.graphviz.org\/doc\/info\/lang.html'/'dot-language'/g \
-e s/'http:\/\/www.graphviz.org\/Documentation\/html\/layers\/'/'graphviz-layered-drawing'/g \
-e s/'http:\/\/www.graphviz.org\/Documentation\/html\/shapehowto.html'/'\/Documentation\/html\/shapehowto.html'/g \
-e s/'http:\/\/www.graphviz.org\/doc\/info\/output.html'/'output-formats'/g \
-e s/'http:\/\/www.graphviz.org\/Documentation'/'\/Documentation'/g \
-e s/"output.html"/"output-formats"/g -e s/"attrs.html"/"attrs"/g  -e s/'SRC=\"'/'SRC=\"\/doc\/info\/'/g  \
| sed -e s/"colors.html"/"color-names"/g -e s/"shapes.html"/"node-shapes"/g \
-e s/"command.html"/"command-line-invocation"/g \
-e s/"en.wikipedia.org\/wiki\/Point_(typography)"/"en.wikipedia.org\/wiki\/Point_(typography) target="_blank""/g \
-e s/"cab38\/ColorBrewer\/ColorBrewer_intro.html"/"cab38\/ColorBrewer\/ColorBrewer_intro.html target="_blank""/g \
> attrs_db


