#! /bin/bash

dir="/home/dperry/graphviz2/doc/info"
cat ${dir}/colors.html | sed -e /"DOCTYPE HTML"/,/"BODY BGCOLOR"/d -e /"Color Names<\/H1>"/d \
-e /"<\/BODY>"/d -e /"<\/HTML>"/d | \
sed -e s/"d:"/"d"/g -e s/"attrs.html"/"attrs"/g \
> colors_db


