SUBDIRS = cdt graph agraph cgraph gd pathplan agutil sfio vmalloc ast circogen \
    dotgen fdpgen sfdpgen neatogen pack twopigen common gvc ingraphs expr

all install clean :
	(for i in ${SUBDIRS}; do (cd $$i; make $@); done)

distclean :
	(for i in ${SUBDIRS}; do (cd $$i; make $@); done)       
	rm -rf lib include
