.\" -*- nroff -*-
.\" This manual is for graphviz, a rich set of graph drawing tools, and it
.\" can be distributed under the same terms as the graphviz package.
.\" 
.\" Copyright (C) 2007 Cyril Brulebois <cyril.brulebois@enst-bretagne.fr>
.\"
.TH LIBGRAPHVIZ3\-CONFIG\-UPDATE 7 "May 23, 2007"
.SH "NAME"
libgraphviz3\-config\-update \- tool to maintain graphviz's configuration file

.SH "SYNOPSIS"
\fBlibgraphviz3\-config\-update\fR \fB\-c\fR

.SH "DESCRIPTION"
Graphviz tools are using a configuration file
(\fI/usr/lib/graphviz/config\fR) to get some plugin options. This
command is used in \fBlibgraphviz3\fR and \fBlibgraphviz3\-*\-plugin\fR
packages' maintainer scripts to update this configuration file when
plugins are installed or removed.

.SH "NOTE"
This tools is intended to be used only in maintainer scripts and
it shouldn't be needed to run it manually.

.SH "AUTHOR"
This manual page was written by Cyril Brulebois
<cyril.brulebois@enst\-bretagne.fr> in may 2007. It can be distributed
under the same terms as the graphviz package.
