/* $Id$ $Revision$ */
/* vim:set shiftwidth=4 ts=8: */

/**********************************************************
*      This software is part of the graphviz package      *
*                http://www.graphviz.org/                 *
*                                                         *
*            Copyright (c) 1994-2004 AT&T Corp.           *
*                and is licensed under the                *
*            Common Public License, Version 1.0           *
*                      by AT&T Corp.                      *
*                                                         *
*        Information and Software Systems Research        *
*              AT&T Research, Florham Park NJ             *
**********************************************************/

/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
//windows.h for win machines
#if defined(_WIN32) && !defined(__CYGWIN__)
#define WIN32_LEAN_AND_MEAN 1
#include <windows.h>
#endif
#include <stdio.h>							// Header File For Standard Input/Output ( NEW )
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtkgl.h>
#include <glade/glade.h>
#include <fontconfig/fontconfig.h>
#include "callbacks.h"
#include "regex.h"

// #include "topology.h"
#include <stdlib.h>



#include "gui.h"
#include "menucallbacks.h"
#include "cgraph.h"
#include "abstring.h"

#ifdef G_OS_WIN32
/*gchar *package_prefix = PACKAGE_PREFIX;
gchar *package_data_dir = PACKAGE_DATA_DIR;
gchar *package_locale_dir = PACKAGE_LOCALE_DIR;*/
#endif
gchar *package_prefix = "";
gchar *package_data_dir = "";
gchar *package_locale_dir = "";

//973 768 8826
//ramy 99 win

int
main (int argc, char *argv[])
{

//	DWORD t1,t2;
	int i=0;
	int ind=0;
	regex_t a;
	GdkGLConfig *glconfig;
	gchar *pixmap_dir;
//	HMODULE mymodule;
	char lpFilename[1024];
	GtkWidget* do_widget=NULL;
	char str[50]="asdasdasasdas";
	//topview test starts here**************	
//	c_interface_draw(5);
	//testme(&str);
//	if(c_interface_load_from_file("c:/4elt.dot",graph,nvtxs,nedges,coords,labels,identifiers)!=0)
	//	c_interface_tp(graph,nvtxs,nedges,coords,labels,identifiers,&hierarchy);
/*	{
		for (ind=0;ind < 100 ;ind++)
		{
			printf("%i:  coords:(%f,%f) ",ind ,coords[0][ind],coords[1][ind]);
//			printf("TVcoords:(%f,%f)\n",hierarchy.geom_graphs[1][ind].x_coord,hierarchy.geom_graphs[1][ind].y_coord);
		}
	}*/

	//topview test end here **************	
	load_attributes();
	
//pango test
//t1=GetTickCount();
//		pango_main("c:/normal.png");
	//****
//	t2=GetTickCount();
//	printf("recorded tickcounts  %d-%d \n", t1,t2);
//	printf("difference (Pango):%d \n", t2-t1);
//    print_children(tree_from_filter_string("(([color=\"brown\",min=\"0\",max=\"30\"])&([color=\"sfsdf\",min=\"15\",max=\"20\"]|[color=\"qqqqq\",min=\"0\",max=\"30\"]))"));

#ifdef G_OS_WIN32
	package_prefix = g_win32_get_package_installation_directory (NULL, NULL);
	package_data_dir = g_build_filename (package_prefix, "share", NULL);
	package_locale_dir = g_build_filename (package_prefix, "share", "locale", NULL);
#endif#
#ifdef ENABLE_NLS
	bindtextdomain (GETTEXT_PACKAGE, package_locale_dir);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
#endif
 //	mymodule=GetModuleHandle(NULL);
//	GetModuleFileName(NULL,lpFilename,1024);
//	printf("dir:%s\n",lpFilename);
//	printf("pango version is %s\n",pango_version_string ());
	gtk_set_locale ();
	gtk_init (&argc, &argv);

#ifdef _WIN32
#define SMYRNA_ICONSDIR "C:\\Projects\\ATT\\GTK\\GTKTest2\\GUI\\images\\"
#endif
//	pixmap_dir = g_build_filename (package_data_dir, "", "pixmaps", NULL);
	printf("pixmap dir:%s \n", SMYRNA_ICONSDIR);
	add_pixmap_directory (SMYRNA_ICONSDIR);
//  add_pixmap_directory ("C:\\Projects\\ATT\\GTK\\GTKTest2\\GUI\\images\\");
//	g_free (pixmap_dir);

	xml = glade_xml_new(SMYRNA_GLADE, NULL, NULL);
	gladewidget = glade_xml_get_widget(xml, "frmMain");
    gtk_widget_show (gladewidget);
	g_signal_connect ((gpointer) gladewidget, "destroy", G_CALLBACK(mQuitSlot),
                    NULL);
	glade_xml_signal_autoconnect(xml);

	gtk_gl_init (0,0);
  /* Configure OpenGL framebuffer. */
	glconfig = configure_gl ();
	gladewidget = glade_xml_get_widget(xml, "vbox2");


	create_window (glconfig,gladewidget);
	gtk_main ();

#ifdef G_OS_WIN32
	g_free (package_prefix);
	g_free (package_data_dir);
	g_free (package_locale_dir);
#endif
	return 0;
}
