ALL = libingraphs.a

all : $(ALL)

include ../../Config.mk
include ../../makearch/$(ARCH)

LOC_INCDIR=../include
LOC_LIBDIR=../lib

DEFINES = -DHAVE_CONFIG_H

INCS =  -I. -I../.. -I../../agraph -I../../graph -I../../cdt

libingraphs.a : ingraphs.o
	$(AR) cr $@ ingraphs.o
	$(MKPATH) $(LOC_INCDIR)
	cp ingraphs.h $(LOC_INCDIR)
	$(MKPATH) $(LOC_LIBDIR)
	cp libingraphs.a $(LOC_LIBDIR)

install : $(ALL)
	$(MKPATH) $(INCDIR)
	cp ingraphs.h $(INCDIR)
	$(MKPATH) $(LIBDIR)
	cp $(ALL_LIB) $(LIBDIR)

clean :
	$(RM) *.o 

distclean : clean
	$(RM) $(ALL)
