CFLAGS=`pkg-config --cflags cairo poppler-glib`
LDFLAGS=`pkg-config --libs cairo poppler-glib`

all: pdftops pdftoimage hello.png

pdftops: pdftops.c

pdftoimage: pdftoimage.c

hello.png: pdftoimage hello.pdf
	./pdftoimage hello.pdf hello.png 1

hello.pdf:
	echo 'digraph {hello->world}' | dot -Tpdf -o hello.pdf

clean:
	rm -f pdftops pdftoimage hello.*
