all:	libfdp.a

include ../../Config.mk
include ../../makearch/$(ARCH)

INCS =  -I. -I../.. \
    -I../common \
    -I../neatogen \
    -I../pack \
    -I../gvrender \
    -I../../pathplan \
    -I../../graph \
    -I../../cdt \
    -I../../gd

DEFINES = -DDEBUG -DHAVE_CONFIG_H

OBJS = layout.o fdpinit.o comp.o tlayout.o xlayout.o dbg.o options.o grid.o \
       clusteredges.o

HFILES = fdp.h 

libfdp.a : $(OBJS)
	$(RM) libfdp.a
	$(AR) cr libfdp.a $(OBJS)
	$(RANLIB) libfdp.a

$(OBJS) : $(HFILES)

install: libfdp.a
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libfdp.a $(LIBDIR)

clean:
	$(RM) *.o core *.a

distclean: clean
	$(RM) lib*.so.*
