.TH CLARIFY 1 "26 February 2014"
.SH NAME
edgepaint \- edge coloring to disambiguate crossing edges
.SH SYNOPSIS
.B 
[
.I options
]
[
.BI \-o
.I outfile
]
[ 
.I files
]
.SH DESCRIPTION
.B edgepaint
takes as input a graph in DOT format with node position information (the \fIpos\fP attribute) and
colors the edges in a manner making it easier to tell them apart.
.SH OPTIONS
The following options are supported:
.TP
.BI \-accuracy=  e 
accuracy with which to find the maximally different coloring for each node with regard to its neighbors. Default e = 0.01. 
.TP
.BI \-angle= a
color two edges differently if their incidence angle is less than \fIa\fP degrees. Default \fIa\fP=15.
.TP
.BI \-random_seed= s 
random seed to use. \fIs\fP must be an integer. If \fIs\fP is negative, we do |\fIs\fP| iterations with different seeds and pick the best. 
.TP
.BI \-lightness= "l1,l2j"
only applies for the "lab" color scheme: \fIl1\fP and \fIl2\fP must integers, with 0 <= \fIl1\fP <= \fIl2 <=100. By default, we use "0,70" 
.TP
.BI \-share_endpoint
if this option is specified, edges that shares an node are not considered in conflict if they are close to parallel but 
are on the opposite sides of the node (around 180 degree). 
.TP
.BI \-o " f"  
write output to file f (default: stdout).
.TP
.BI \-color_scheme= "c"
specifies the color scheme.  This can be "rgb", "gray", "lab" (default);
or a comma-separated list of RGB colors in hex (e.g., "#ff0000,#aabbed,#eeffaa") representing a palette;
or a string specifying a Brewer color scheme (e.g., "accent7"; see http://www.graphviz.org/content/color-names#brewer).
.TP
.B \-v 
turns on verbose mode.
.TP
.BI \-? 
Print usage and exit.

.SH BUGS
At present, \fBedgepaint\fP does not handle graphs with loops or directed multiedges. So, a graph with edges
\fIa -> b\fP and \fIb -> a\fP is acceptable, but not if it has edges \fIa -> b\fP and \fIa -> b\fP or
\fIa -- b\fP and \fIa -- b\fP.
.SH AUTHOR
Yifan Hu <yifanhu@research.att.com>
.SH "SEE ALSO"
.PP
gvmap(1), sfdp(1), neato (1), dot(1)
.PP

