.TH GXL2DOT,DOT2GXL 1 "20 December 2002"
.SH NAME
gxl2dot,dot2gxl \- GXL-DOT converters
.SH SYNOPSIS
.B gxl2dot
[
.B \-gd?
]
[
.BI -o outfile
]
[ 
.I files
]
.br
.B dot2gxl
[
.B \-gd?
]
[
.BI -o outfile
]
[ 
.I files
]
.SH DESCRIPTION
.B gxl2dot
converts between graphs represented in GXL and in the
DOT language. Unless a conversion type is specified using
a flag,
.B gxl2dot
will deduce the type of conversion from the suffix of
the input file, a ".dot" suffix causing a conversion from DOT
to GXL, and a ".gxl" suffix causing a conversion from GXL to DOT.
If no suffix is available, e.g. when the input is from a pipe,
and no flags are used then
.B gxl2dot
assumes the type of the input file from its executable name
so that
.B gxl2dot
converts from GXL to DOT, and
.B dot2gxl
converts from DOT to GXL.
.PP
GXL supports a much richer graph model than DOT. \fBgxl2dot\fP
will attempt to map GXL constructs into the analogous DOT construct
when this is possible. If not, the GXL information is stored as
an attribute. The intention is that applying \fBgxl2dot|dot2gxl\fP
is semantically equivalent to the identity operator.
.SH OPTIONS
The following options are supported:
.TP
.B \-g
The command name and input file extensions are ignored, the
input is taken as a DOT file and a GXL file is generated.
.TP
.B \-d
The command name and input file extensions are ignored, the
input is taken as a GXL file and a DOT file is generated.
.TP
.B \-?
Prints usage information and exits.
.TP
.BI \-o " outfile"
If specified, the output will be written into the file
\fIoutfile\fP. Otherwise, output is written to standard out.
.SH OPERANDS
The following operand is supported:
.TP 8
.I files
Names of files containing 1 or more graphs in GXL or DOT.
If no
.I files
operand is specified,
the standard input will be used.
.SH RETURN CODES
Both \fBgxl2dot\fP and \fBdot2gxl\fP return \fB0\fP
if there were no problems during conversion;
and non-zero if any error occurred.
.SH "BUGS"
\fBgxl2dot\fP will only convert in one direction even if given multiple files
with varying suffixes.
.PP
The conversion can only handle one graph per GXL file.
.PP
There are some GXL constructs which \fBgxl2dot\fP cannot handle.
.SH AUTHORS
Krishnam Pericherla <kp@research.att.com>
.br
Emden R. Gansner <erg@research.att.com>
.SH "SEE ALSO"
dot(1), libgraph(3), libagraph(3), neato(1), twopi(1)
