find_path(RXSPENCER_INCLUDE_DIR regex.h)
find_library(RXSPENCER_LIBRARY NAMES rxspencer)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(RXSPENCER DEFAULT_MSG
    RXSPENCER_LIBRARY
    RXSPENCER_INCLUDE_DIR
)

mark_as_advanced(
    RXSPENCER_INCLUDE_DIR
    RXSPENCER_LIBRARY
)

set(RXSPENCER_INCLUDE_DIRS ${RXSPENCER_INCLUDE_DIR})
set(RXSPENCER_LIBRARIES ${RXSPENCER_LIBRARY})
