SET(top_SRCDIR ${CMAKE_SOURCE_DIR})
SET(awk_SRCDIR ${CMAKE_SOURCE_DIR}/awk)

SET(ast_SRCDIR ${CMAKE_SOURCE_DIR}/lib/ast)
SET(agraph_SRCDIR ${CMAKE_SOURCE_DIR}/lib/agraph)
SET(agutil_SRCDIR ${CMAKE_SOURCE_DIR}/lib/agutil)
SET(cdt_SRCDIR ${CMAKE_SOURCE_DIR}/lib/cdt)
SET(circogen_SRCDIR ${CMAKE_SOURCE_DIR}/lib/circogen)
SET(common_SRCDIR ${CMAKE_SOURCE_DIR}/lib/common)
SET(dotgen_SRCDIR ${CMAKE_SOURCE_DIR}/lib/dotgen)
SET(expr_SRCDIR ${CMAKE_SOURCE_DIR}/lib/expr)
SET(fdpgen_SRCDIR ${CMAKE_SOURCE_DIR}/lib/fdpgen)
SET(graph_SRCDIR ${CMAKE_SOURCE_DIR}/lib/graph)
SET(gd_SRCDIR ${CMAKE_SOURCE_DIR}/lib/gd)
SET(gvc_SRCDIR ${CMAKE_SOURCE_DIR}/lib/gvc)
SET(ingraphs_SRCDIR ${CMAKE_SOURCE_DIR}/lib/ingraphs)
SET(neatogen_SRCDIR ${CMAKE_SOURCE_DIR}/lib/neatogen)
SET(pack_SRCDIR ${CMAKE_SOURCE_DIR}/lib/pack)
SET(pathplan_SRCDIR ${CMAKE_SOURCE_DIR}/lib/pathplan)
SET(sfio_SRCDIR ${CMAKE_SOURCE_DIR}/lib/sfio)
SET(twopigen_SRCDIR ${CMAKE_SOURCE_DIR}/lib/twopigen)
SET(vmalloc_SRCDIR ${CMAKE_SOURCE_DIR}/lib/vmalloc)
SET(vpsc_SRCDIR ${CMAKE_SOURCE_DIR}/lib/vpsc)

SET(gvplugin_core_SRCDIR ${CMAKE_SOURCE_DIR}/plugin/core)
SET(gvplugin_dot_layout_SRCDIR ${CMAKE_SOURCE_DIR}/plugin/dot_layout)
SET(gvplugin_gd_SRCDIR ${CMAKE_SOURCE_DIR}/plugin/gd)
SET(gvplugin_gtk_SRCDIR ${CMAKE_SOURCE_DIR}/plugin/gtk)
SET(gvplugin_neato_layout_SRCDIR ${CMAKE_SOURCE_DIR}/plugin/neato_layout)
SET(gvplugin_pango_SRCDIR ${CMAKE_SOURCE_DIR}/plugin/pango)
SET(gvplugin_xlib_SRCDIR ${CMAKE_SOURCE_DIR}/plugin/xlib)

SET(gdtclft_SRCDIR ${CMAKE_SOURCE_DIR}/tclpkg/gdtclft)
SET(gv_SRCDIR ${CMAKE_SOURCE_DIR}/tclpkg/gv)
SET(tcldot_SRCDIR ${CMAKE_SOURCE_DIR}/tclpkg/tcldot)
SET(tclhandle_SRCDIR ${CMAKE_SOURCE_DIR}/tclpkg/tclhandle)
SET(tclpathplan_SRCDIR ${CMAKE_SOURCE_DIR}/tclpkg/tclpathplan)
SET(tclstubs_SRCDIR ${CMAKE_SOURCE_DIR}/tclpkg/tclstubs)
SET(tkstubs_SRCDIR ${CMAKE_SOURCE_DIR}/tclpkg/tkstubs)
SET(tkspline_SRCDIR ${CMAKE_SOURCE_DIR}/tclpkg/tkspline)

SET(dot_SRCDIR ${CMAKE_SOURCE_DIR}/cmd/dot)
SET(dotty_SRCDIR ${CMAKE_SOURCE_DIR}/cmd/dotty)
SET(gvpr_SRCDIR ${CMAKE_SOURCE_DIR}/cmd/gvpr)
SET(lefty_SRCDIR ${CMAKE_SOURCE_DIR}/cmd/lefty)
SET(lneato_SRCDIR ${CMAKE_SOURCE_DIR}/cmd/lneato)
SET(tools_SRCDIR ${CMAKE_SOURCE_DIR}/cmd/tools)
