CC       := gcc
LIBTOOL  := libtool
LIBTOOL  := splint
OPTFLAGS := -O3

GRAPHVIZ_DIR  := ../graphviz
GRAPHVIZ_INC  := agraph cdt tools/src
GRAPHVIZ_LIBS := agraph/libagraph.la cdt/libcdt.la tools/src/libingraphs.la

CFLAGS   := -Wall -I. $(patsubst %, -I$(GRAPHVIZ_DIR)/%, $(GRAPHVIZ_INC))
LDFLAGS  := $(patsubst %, $(GRAPHVIZ_DIR)/%, $(GRAPHVIZ_LIBS))


DESTDIR :=

prefix  := /usr/local
bindir  := $(prefix)/bin
man1dir := $(prefix)/man/man1

ifdef MPATROL
  LDFLAGS += -lmpatrol -lbfd -liberty
endif

all: prune

prune.o: prune.c generic_list.h

generic_list.o: generic_list.c generic_list.h

prune: prune.o generic_list.o
	$(LIBTOOL) --mode=link $(CC) -o $@ $^ $(LDFLAGS)

.PHONY: lint
lint:
	$(LINT) $(INCLUDES) +posixlib prune.c generic_list.c

.PHONY: gdb
gdb:
	make prune OPTFLAGS=-g
	gdb ./prune --directory $(GRAPHVIZ_DIR)/tools/src --directory $(GRAPHVIZ_DIR)/agraph

.PHONY: install
install: prune
	install -d $(DESTDIR)$(bindir) $(DESTDIR)$(man1dir)
	install -m 0755 prune   $(DESTDIR)$(bindir)
	install -m 0644 prune.1 $(DESTDIR)$(man1dir)

.PHONY: clean
clean:
	-rm -f prune *.o
