all:	libgvplugin_gdk.a
ROOT=../..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =  -I. \
	-I$(ROOT) \
        -I../../lib/common \
        -I../../lib/pathplan \
        -I../../lib/graph \
        -I../../lib/cdt \
        -I../../lib/gvc 

DEFINES = -DHAVE_CONFIG_H

OBJS = gvformatter_gdk.o gvplugin_gdk.o

libgvplugin_gdk.a : $(OBJS)
	$(RM) libgvplugin_gdk.a
	$(AR) cr libgvplugin_gdk.a $(OBJS)
	$(RANLIB) libgvplugin_gdk.a

install: libgvplugin_gdk.a
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libgvplugin_gdk.a $(LIBDIR)

clean:
	$(RM) core *.o

distclean: clean
	$(RM) *.a ptest
