all:	libosage.a
ROOT=../..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I. -I$(ROOT) \
	-I../common \
	-I../neatogen \
	-I../sparse \
	-I../pack \
	-I../gvc \
	-I../fdpgen \
	-I../pathplan \
	-I../graph \
	-I../cdt \
	-I../gd

DEFINES = -DHAVE_CONFIG_H

OBJS = osageinit.o

HFILES = osage.h 

libosage.a : $(OBJS)
	$(RM) libosage.a
	$(AR) cr libosage.a $(OBJS)
	$(RANLIB) libosage.a

$(OBJS) : $(HFILES) ../common/types.h

install: libosage.a
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libosage.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
